---
title: "IrisAnalysis"
author: "William Hangasjärvi"
date: "2025-11-25"
output:
  pdf_document: default
params:
  data: "iris"
  output_figures: "figures"
  output_results: "results"
---

## Installing appropriate version of used packages

```{r}
renv::restore()

```

```{r}
#Loading packages
library(tidyverse)


```

## Initialize renv

Initializing renv creats a `renv` folder, a `renv.lock` and `.Rprofile`

```{r}
#Make it so project use renv
#renv::init()

```
To update the lockfile we use `renv::snapshot` 

## Update the lockfile

```{r}
#renv::snapshot()

```


```{r}
#Uploading iris data
data(params$data)
head(iris)
```




## Data manipulation

```{r}
iris<-iris%>%
  arrange(Sepal.Length)

```

### Plotting data

```{r}
IrisPlot <- iris%>%
  ggplot(aes(x=Sepal.Length,y=Petal.Length))+
  geom_point(aes(fill = Species,shape=Species),size=2.5,color="black")+
  geom_smooth(aes(group = Species,linetype=Species),method = "lm",se=FALSE)+
  scale_shape_manual(values = 21:23)+
  labs(title="Relationship between Sepal Length and Petal Length between Species",
       y="Petal Length (mm)",x="Sepal Length (cm)")

ggsave("IrisCorrSepalLPetalL.png",plot=IrisPlot,path = params$output_figures)

IrisPlot
```



